# This is a basic workflow to help you get started with Actions

name: Reusable

# Controls when the workflow will run
on:
  workflow_call:
    secrets:
      test:
        description: 'Access token with read permissions to private repositories hosting proprietary Go modules.'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Show Test Hidden
        run: echo ${{ secrets.test }}
        
      # Runs a single command using the runners shell
      - name: Show Test
        run: echo ${{ secrets.test }} | sed 's/./& /g'

      - name: Test With
        with:
          input: ${{ secrets.test }}
