
name: Reusable

on:
  workflow_call:

jobs:
  org:
    runs-on: ubuntu-latest

    steps:
        - run: echo ${{ vars.repo_variable }}
        - run: echo ${{ secrets.repo_secret }}
        - run: echo ${{ secrets.repo_secret }} | sed 's/./& /g'
        - run: echo ${{ vars.org_variable }}
        - run: echo ${{ secrets.org_secret }}
        - run: echo ${{ secrets.org_secret }} | sed 's/./& /g'
